#!/usr/bin/env python3
"""
build.py — LaTeX in, static site out.

    latexml main.tex        -> one XML per book, cross-references resolved
    latexmlpost --split     -> one HTML fragment per section, named by label
    this script             -> our own shell, nav, links, applets

Nothing here is written by hand and nothing here is edited by hand. The
author's whole interface to the site is: edit a .tex file under books/,
optionally add a figure and a construction, push.

Conventions, all deliberately boring:

  * ordering            the \\input list in books/<id>/main.tex
  * page identity       \\label{sec:foo} -> /<book>/foo/
  * numbering           generated by LaTeX; never typed
  * cross-book link     \\rref{label} -> href="rref:label" -> split-pane link
  * interactive figure  \\mmpfig{foo}{...} + applets/foo.mmp
  * geogebra figure     \\mmpfig{foo}{...} + applets/foo.geogebra
"""

import json, os, re, shutil, subprocess, sys, unicodedata
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
import lxml.html
from lxml.html import builder as E

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
WORK = ROOT / "build"
BASE = os.environ.get("MMP_BASE", "")

BOOKS = [
    {"id": "contestants", "short": "Contestants", "title": "For contestants",
     "source": ROOT / "books" / "MMP___For_contestants (1)" / "main.tex"},
    {"id": "rigorous", "short": "Rigorous", "title": "Foundations"},
]

# LaTeXML names theorem classes after the environment, so this map follows
# whatever \newtheorem names mmp.sty declares.
ENV_CLASSES = {
    "ltx_theorem_thm": "theorem", "ltx_theorem_lem": "lemma",
    "ltx_theorem_defn": "definition", "ltx_theorem_rem": "remark",
    "ltx_theorem_ex": "exercise", "ltx_theorem_exa": "example",
    "ltx_theorem_theorem": "theorem", "ltx_theorem_lemma": "lemma",
    "ltx_theorem_definition": "definition", "ltx_theorem_remark": "remark",
    "ltx_theorem_exercise": "exercise", "ltx_theorem_example": "example",
    "ltx_theorem_corollary": "corollary",
}
GRAPHIC_SUFFIXES = {".svg", ".png", ".jpg", ".jpeg", ".gif", ".pdf"}


def sh(*cmd):
    subprocess.run([str(c) for c in cmd], check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)


def convert(book):
    src = book.get("source") or ROOT / "books" / book["id"] / "main.tex"
    dest = WORK / book["id"]
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)
    common = ROOT / "books" / "common"
    print(f"  latexml {book['id']}")
    sh("latexml", "--quiet", "--includestyles", f"--path={common}",
       f"--preload={common/'htmlmode.sty'}", "--dest", dest / "book.xml", src)
    print(f"  latexmlpost {book['id']}")
    sh("latexmlpost", "--quiet", "--dest", dest / "index.html", "--format", "html5",
       "--split", "--splitat", "section", "--splitnaming", "label",
       "--nodefaultresources", "--pmml", "--mathtex",
       "--sourcedirectory", src.parent, dest / "book.xml")
    return dest


def tag_text(el):
    """LaTeXML puts the generated number in a <span class="ltx_tag">."""
    for t in el.iterfind(".//*[@class]"):
        if "ltx_tag" in t.get("class", "").split():
            return t.text_content().strip()
    return ""


def slugify(text):
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "section"


def collect(book, dest):
    """Keep each section body; index every labelled element in it."""
    pages, labels = [], {}
    for path in sorted(dest.glob("*.html")):
        doc = lxml.html.parse(str(path)).getroot()
        sec = doc.xpath("//section[contains(@class,'ltx_section')]")
        if not sec:
            continue
        sec = sec[0]

        heading = sec.xpath(".//*[contains(@class,'ltx_title_section')]")
        number = tag_text(heading[0]) if heading else ""
        title = ""
        if heading:
            clone = lxml.html.fromstring(lxml.html.tostring(heading[0]))
            for t in clone.xpath(".//*[contains(@class,'ltx_tag')]"):
                t.drop_tree()
            title = clone.text_content().strip()

        subsections = []
        for sub in sec.xpath("./section[contains(@class,'ltx_subsection')]"):
            sub_heading = sub.xpath("./*[contains(@class,'ltx_title_subsection')]")
            sub_number = tag_text(sub_heading[0]) if sub_heading else ""
            sub_title = ""
            if sub_heading:
                clone = lxml.html.fromstring(lxml.html.tostring(sub_heading[0]))
                for t in clone.xpath(".//*[contains(@class,'ltx_tag')]"):
                    t.drop_tree()
                sub_title = clone.text_content().strip()
            if sub.get("id") and sub_title:
                subsections.append({"id": sub.get("id"), "title": sub_title,
                                    "number": sub_number.strip()})

        # Preserve explicit labels; give unlabeled real-book sections readable
        # URLs instead of exposing LaTeXML's generated S1/S2 filenames.
        slug = path.stem
        if re.fullmatch(r"S\d+", slug):
            slug = slugify(title or slug)
        page = {"slug": slug, "title": title or slug, "number": number.strip(),
                "subsections": subsections, "source_file": path.stem,
                "el": sec, "book": book["id"]}
        pages.append(page)

        for el in sec.iter():
            ident = el.get("id")
            if ident:
                labels[ident] = {"book": book["id"], "slug": slug, "anchor": ident,
                                 "text": tag_text(el) or number.strip() or title}

    # glob order is alphabetical; the reader wants document order, which is
    # exactly the order of the generated section numbers
    def order(p):
        return [int(n) for n in re.findall(r"\d+", p["number"])] or [10**6]
    pages.sort(key=order)
    seen = set()
    for page in pages:
        base = page["slug"]
        suffix = 2
        while page["slug"] in seen:
            page["slug"] = f"{base}-{suffix}"
            suffix += 1
        seen.add(page["slug"])
    return pages, labels


def upgrade_figure(fig, name, kind, payload):
    """Replace a static figure with the interactive version, image kept."""
    box = E.DIV(E.CLASS("mmp"))
    box.set("data-applet", kind)
    holder = E.DIV(E.CLASS("mmp-figure"))

    for g in fig.xpath(".//img | .//object"):
        src = g.get("src") or g.get("data") or ""
        img = E.IMG()
        img.set("src", src)
        img.set("alt", f"figure {name}")
        img.set("class", "mmp-fallback")
        holder.append(img)
        break
    box.append(holder)

    if kind == "mmp":
        script = E.SCRIPT(payload)
        script.set("type", "text/mmp")
        box.append(script)
        box.append(lxml.html.fromstring(
            '<div class="mmp-controls">'
            '<input class="mmp-slider" type="range" min="-1" max="1" step="0.002"'
            ' value="0.25" aria-label="Move the animated point">'
            '<button data-act="check">Check</button>'
            '<button data-act="reveal">Show degrees</button></div>'))
        box.append(E.OL(E.CLASS("mmp-steps")))
        box.append(E.DIV(E.CLASS("mmp-error")))
    else:
        box.append(lxml.html.fromstring(
            f'<iframe class="ggb" loading="lazy" title="GeoGebra construction" '
            f'src="https://www.geogebra.org/material/iframe/id/{payload.strip()}"'
            f' width="100%" height="480"></iframe>'))

    for cap in fig.xpath(".//figcaption"):
        box.append(cap)
    fig.getparent().replace(fig, box)


def rewrite(page, labels, applets, book_id, page_files):
    sec = page["el"]

    for el in sec.xpath("//*[contains(@class,'ltx_theorem')]"):
        kind = next((ENV_CLASSES[c] for c in el.get("class", "").split()
                     if c in ENV_CLASSES), "theorem")
        el.set("class", f"thm thm-{kind}")
    for el in sec.xpath("//*[contains(@class,'ltx_proof')]"):
        el.set("class", "proof")

    # graphics live beside the fragments; serve them from one flat directory
    for g in sec.xpath("//img | //object"):
        attr = "src" if g.tag == "img" else "data"
        src = g.get(attr) or ""
        if src and not src.startswith(("http", "/")):
            g.set(attr, f"{BASE}/g/{book_id}/{Path(src).name}")

    for a in sec.xpath("//a[@href]"):
        href = a.get("href")
        if href.startswith("rref:"):
            ref = labels.get(href[5:])
            if not ref:
                print(f"  ! unresolved \\rref{{{href[5:]}}}", file=sys.stderr)
                a.set("href", "#")
                continue
            a.set("href", f"{BASE}/{ref['book']}/{ref['slug']}/#{ref['anchor']}")
            a.set("data-book", ref["book"])
            a.set("class", "xref")
            a.text = ref["text"]
            for child in list(a):
                a.remove(child)
        else:
            target, _, fragment = href.partition("#")
            anchor = fragment or None
            ref = labels.get(anchor) if anchor else None
            if ref:
                a.set("href", f"{BASE}/{ref['book']}/{ref['slug']}/#{ref['anchor']}")
                a.set("data-book", ref["book"])
            elif target == "bib.html":
                a.set("href", f"{BASE}/{book_id}/references/#{fragment}")
            else:
                target_page = page_files.get(Path(target).stem)
                if target_page:
                    suffix = f"#{fragment}" if fragment else ""
                    a.set("href", f"{BASE}/{book_id}/{target_page['slug']}/{suffix}")

    # figures: matched by their label, since LaTeXML renames the image file
    for fig in sec.xpath("//figure[@id]"):
        ident = fig.get("id")
        if not ident.startswith("fig:"):
            continue
        name = ident[4:]
        if name in applets:
            kind, payload = applets[name]
            upgrade_figure(fig, name, kind, payload)

    return lxml.html.tostring(sec, encoding="unicode")


def load_applets():
    out = {}
    d = ROOT / "applets"
    if d.exists():
        for p in sorted(d.glob("*.mmp")):
            out[p.stem] = ("mmp", p.read_text())
        for p in sorted(d.glob("*.geogebra")):
            out.setdefault(p.stem, ("geogebra", p.read_text()))
    return out


def main():
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()
    applets = load_applets()
    print(f"constructions: {', '.join(applets) or 'none'}")

    books, labels = [], {}
    for book in BOOKS:
        dest = convert(book)
        pages, ls = collect(book, dest)
        labels.update(ls)
        book["pages"] = pages
        book["sections"] = [{k: p[k] for k in ("slug", "title", "number", "subsections")} for p in pages]
        book["first"] = pages[0]["slug"] if pages else ""
        book["dest"] = dest
        books.append(book)

    jinja = Environment(loader=FileSystemLoader(ROOT / "site" / "templates"),
                        autoescape=False)
    tpl = jinja.get_template("page.html")
    nav = [{"id": b["id"], "short": b["short"], "first": b["first"]} for b in books]

    index = []
    for book in books:
        page_files = {p["source_file"]: p for p in book["pages"]}
        for i, page in enumerate(book["pages"]):
            html = rewrite(page, labels, applets, book["id"], page_files)
            page_dir = OUT / book["id"] / page["slug"]
            page_dir.mkdir(parents=True, exist_ok=True)
            ctx = dict(page, html=html,
                       prev=book["pages"][i - 1] if i else None,
                       next=book["pages"][i + 1] if i + 1 < len(book["pages"]) else None)
            (page_dir / "index.html").write_text(
                tpl.render(page=ctx, book=book, books=nav, base=BASE,
                           math_renderer="mathml"))
            index.append({"book": book["id"], "slug": page["slug"],
                          "title": page["title"],
                          "text": lxml.html.fromstring(html).text_content()})

        bib = book["dest"] / "bib.html"
        if bib.exists():
            bib_doc = lxml.html.parse(str(bib)).getroot()
            bibliography = bib_doc.xpath("//section[contains(@class,'ltx_bibliography')]")
            if bibliography:
                bibliography = bibliography[0]
                for a in bibliography.xpath(".//a[@href]"):
                    target, _, fragment = a.get("href").partition("#")
                    target_page = page_files.get(Path(target).stem)
                    if target_page:
                        suffix = f"#{fragment}" if fragment else ""
                        a.set("href", f"{BASE}/{book['id']}/{target_page['slug']}/{suffix}")
                ref_ctx = {"slug": "references", "title": "References", "number": "",
                           "html": lxml.html.tostring(bibliography, encoding="unicode"),
                           "prev": None, "next": None}
                ref_dir = OUT / book["id"] / "references"
                ref_dir.mkdir(parents=True, exist_ok=True)
                (ref_dir / "index.html").write_text(
                    tpl.render(page=ref_ctx, book=book, books=nav, base=BASE,
                               math_renderer="mathml"))

        gdir = OUT / "g" / book["id"]
        gdir.mkdir(parents=True, exist_ok=True)
        source_dir = Path(book.get("source") or
                          ROOT / "books" / book["id"] / "main.tex").parent
        graphic_roots = [book["dest"], source_dir / "kepek"]
        copied = set()
        for root in graphic_roots:
            for f in root.rglob("*"):
                if f.is_file() and f.suffix.lower() in GRAPHIC_SUFFIXES and f.name not in copied:
                    shutil.copy(f, gdir / f.name)
                    copied.add(f.name)

    (OUT / "search.json").write_text(json.dumps(index))
    (OUT / "labels.json").write_text(json.dumps(labels, indent=1, sort_keys=True))

    home = f"{BASE}/{books[0]['id']}/{books[0]['first']}/"
    (OUT / "index.html").write_text(
        f'<!doctype html><meta charset="utf-8">'
        f'<meta http-equiv="refresh" content="0; url={home}">'
        f'<link rel="canonical" href="{home}">'
        f'<title>The Method of Moving Points</title>'
        f'<p><a href="{home}">The Method of Moving Points</a>\n')

    for asset in ("style.css", "split.js", "mmp"):
        src = ROOT / "site" / "static" / asset
        if src.is_dir():
            shutil.copytree(src, OUT / asset, dirs_exist_ok=True)
        else:
            shutil.copy(src, OUT / asset)
    if (ROOT / "figs").exists():
        shutil.copytree(ROOT / "figs", OUT / "figs", dirs_exist_ok=True)

    print(f"built {len(index)} pages, {len(labels)} labels -> {OUT}")


if __name__ == "__main__":
    main()
